# -*- mode: ruby -*-
# vim: set ft=ruby :
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
MACHINES = {
  :nfsserver => {
        :box_name => "ubuntu/22.04",
        :vm_name => "nfsserver",
        :ip => "192.168.10.10",
  },
  :nfsclient => {
        :box_name => "ubuntu/22.04",
        :vm_name => "nfsclient",
        :ip => "192.168.10.20",
  }
}
Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      box.vm.network "private_network", ip: boxconfig[:ip]

      box.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
        v.name = boxconfig[:vm_name]
       end

      # блок для сервера
      if boxname == :nfsserver
        box.vm.provision "shell", privileged: true, inline: <<-SHELL
        apt update
        apt install -y nfs-kernel-server
        mkdir -p /opt/folder
        echo "/opt/folder *(rw,sync,no_subtree_check)" >> /etc/exports
        exportfs -a
        SHELL
      end

      # блок для клиента
      if boxname == :nfsclient
        box.vm.provision "shell", privileged: true, inline: <<-SHELL
        apt update
        apt install -y nfs-common
        mount -t nfs 192.168.10.10:/opt/folder /mnt
        SHELL
      end

    end
  end
end