# -*- mode: ruby -*-
# vim: set ft=ruby :
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
MACHINES = {
  :proc => {
        :box_name => "bento/ubuntu-24.04",
        :vm_name => "proc",
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]


      box.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2

       end

      box.vm.provision "shell", privileged: true, inline: <<-SHELL

      SHELL
    end
  end
end